Description: >
    Donko Dimov / cloud devops course from Udacity.com
    VPC template for deploying on AWS
Resources:
    UdacityVPC:
        Type: AWS::EC2::VPC
        Properties: 
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
